query getRepoLanguages($owner: String!, $name: String!, $cursor: String) {
	repository(owner: $owner, name: $name){
		updatedAt
		name
		languages(first:100, after: $cursor){
			totalSize
			totalCount
			edges{
				size
				node{
					name
				}
			}
			pageInfo{
				hasNextPage
				endCursor
			}
		}
	}
}
