query getOrgRepos($organization: String!, $repocursor: String){
				organization(login:$organization){
					repositories(first: 100, after: $repocursor){
						totalCount
						edges {
							node {
                                name
								nameWithOwner
								url
								visibility
                                }
							}
                        pageInfo {
							endCursor
							hasNextPage
							}
						}
                    }
				}