query getRepoCollaborators($owner: String!, $name: String!, $collabcursor: String) {
	repository(owner:$owner, name:$name) {
		nameWithOwner
		url
		visibility
		collaborators(first: 100, after: $collabcursor){
			edges {
				permission
				node{
					login
				}
			}
            pageInfo{
                hasNextPage
                endCursor
            }
		}
	}
}