query getEnterpiseOrgs($slug: String!, $cursor: String) {
	enterprise(slug: $slug) {
		name
		url
		organizations(first: 1, after: $cursor) {
			nodes {
				name
				login
				url
				id
			}
			pageInfo {
				hasNextPage
				endCursor
			}
		}
	}
}